### ISSUE TITLE
CLI Example?

### ISSUE THREAD

**Issue by peterdutton** [ThibWeb/export-svg-chart#1]
Hi,

I've been trying to get this working but can't seem to. 

First I saved the example code from the README.md, and then tried:

`node basic.js`

but this resulted in no output.

Then I realised that this is meant to use electron, so I tracked down the electron code in ~/node_modules/ and tried:

`~/node_modules/electron/cli.js basic.js`

but then I got an error as follows:

`$ ~/node_modules/electron/cli.js basic.js
TypeError: Bad argument
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:399:9)
    at Nightmare.queue (/home/peter/node_modules/nightmare/lib/nightmare.js:123:22)
    at next (/home/peter/node_modules/nightmare/lib/nightmare.js:341:12)
    at Nightmare.run (/home/peter/node_modules/nightmare/lib/nightmare.js:331:3)
    at /home/peter/node_modules/nightmare/lib/nightmare.js:492:10
    at Nightmare.then (/home/peter/node_modules/nightmare/lib/nightmare.js:490:10)
    at /home/peter/node_modules/wrap-fn/node_modules/co/index.js:223:13
    at next (/home/peter/node_modules/wrap-fn/node_modules/co/index.js:90:21)
    at /home/peter/node_modules/wrap-fn/node_modules/co/index.js:45:5`

the script hangs at this point and I have to do Ctrl-C to get the prompt back.

Please can you let me know what I'm doing wrong, and/or provide an example of how to run it on the command line?
(I'm running Ubuntu 16.04 LTS, 64 bit)

Thanks!

**Comment by thibaudcolas** [comment]
Hey @peterdutton, sorry to hear this hasn't worked so far!

I just tried this outside of the main project and got the output I would expect. Here are the steps I followed:

- Install the lib: `npm install export-svg-chart --save`
- Create an example.js file with the code from `examples/basic.js` (just changing the import)

```js
const fs = require('fs');
const exportSvgChart = require('export-svg-chart');

const options = {
    url: 'http://bl.ocks.org/mbostock/raw/7341714/',
    selector: '.chart',
};

exportSvgChart(options, (err, buffers) => {
    if (err) return console.log(err);

    fs.writeFile('basic-example.svg', buffers.svg);
    fs.writeFile('basic-example.png', buffers.png);
});
```

... and finally run this with `node example.js`. I get the two files I would expect from the example:

```sh
$ ls
basic-example.png example.js        package-lock.json
basic-example.svg node_modules      package.json
```

I've also updated the Travis CI build to make sure it does indeed generate the images there as well and it seems to work fine (see https://travis-ci.org/thibaudcolas/export-svg-chart/jobs/246758645, printing the file sizes and the content of the SVG file).

-------

Could you let me know what is displayed when you run `node basic.js`, and whether any images are created in the current directory? Also make sure you are using at least Node 4, as this doesn't support older versions.

Finally, here is a very naive cli interface for this that should work:

```js
#!/usr/bin/env node

// 1. Make this file (say cli.js)
// 2. `chmod +x cli.js`
// 3. ./cli.js https://bl.ocks.org/mbostock/raw/3007180/2f604adf60cc5d1c82426c52471df35bbc2d47a2/ svg
const fs = require('fs');
const exportSvgChart = require('export-svg-chart');
const slugify = require('slugify');

const options = {
    url: process.argv[2],
    selector: process.argv[3],
};

exportSvgChart(options, (err, buffers) => {
    if (err) return console.log(err);

    process.stdout.write(buffers.svg);
});
```

**Comment by peterdutton** [comment]
Hi, thanks so much for the reply.

I have tried this again but I'm still having issues. I had the module already installed, so I removed it and reinstalled as per your instructions. However I had to use 'sudo' to enable the install to complete; this may be the reason why I don't see the same results as you. 

When I try to run the example file, I now get the message "Electron failed to install correctly, please delete node_modules/electron and try installing again".

I have reinstalled electron but still get the same message. I'm going to investigate this now, I'll let you know how it goes.

Thanks again!

**Comment by thibaudcolas** [comment]
👍  Looks like an electron issue. I'll close this for now then, let me know if I can help.
